### ISSUE TITLE
Criar README

### ISSUE THREAD

**Issue by matheusjardimb** [iugu/iugu-magento#1]
Este módulo está pronto?
Se sim, seria legal ter um README explicando a forma de instalação, versão corrente do módulo...

**Comment by matheusjardimb** [comment]
:smile:  bom trabalho

**Comment by smorigo** [comment]
@matheusjardimb você chegou a usar esse modulo?

**Comment by EduardoIugu** [comment]
Documentação criada, espero que ajude a resolver suas dúvidas!
