### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by fatcho** [iugu/iugu-magento#2]
Tentei instalar o modulo mas ao cessar a area de pagamentos no administrador da o seguinte erro:

Fatal error: Class 'Mage_Iugu_Helper_Data' not found in /var/www/webroot/ROOT/app/Mage.php on line 547

**Comment by tavoli** [comment]
como vc fez a instalação?

**Comment by EduardoIugu** [comment]
Por favor consulte o Readme.md criado há alguns dias!
