### ISSUE TITLE
Não compatível com Magento 2

### ISSUE THREAD

**Issue by lucascasotti** [iugu/iugu-magento#5]
Seria bom ter um readme, informando como efetuar a instalação e também indicando quais são as versões compatíveis. Pela estrutura de pastas vi que não é compatível com magento 2. Vou ter que abrir mão da plataforma pela incompatibilidade.

**Comment by EduardoIugu** [comment]
Teremos futuramente uma versão do plugin para Magento 2.x, mas ainda não sabemos quando ficará pronta. Desculpe pelo inconveniente.
